# Generated by Django 4.2.12 on 2024-05-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
